_wandb:
    value:
        cli_version: 0.24.2
        e:
            ysthqykaj0tytvzyy5yhwtf8y96afxis:
                args:
                    - --pretrained_model_name_or_path=/home/xzh/xzh/pretrained/sd_xl_base_1.0
                    - --name=unziplora+M1+M2(fused)
                    - --instance_data_dir=/home/xzh/xzh/UnZipLoRA-fine/instance_data/origami_sunflower
                    - --output_dir=models/origami_sunflower/origami_sunflower
                    - --instance_prompt=A monadikos sunflower in origami style
                    - --content_forward_prompt=A monadikos sunflower
                    - --style_forward_prompt=A sunflower in origami style
                    - --rank=64
                    - --resolution=1024
                    - --train_batch_size=1
                    - --content_learning_rate=0.00005
                    - --style_learning_rate=0.00005
                    - --weight_learning_rate=0.005
                    - --similarity_lambda=0.5
                    - --report_to=wandb
                    - --lr_scheduler=constant
                    - --lr_warmup_steps=0
                    - --max_train_steps=600
                    - --checkpointing_steps=200
                    - --mixed_precision=fp16
                    - --seed=0
                    - --use_8bit_adam
                    - --validation_content=A monadikos sunflower on a table
                    - --validation_style=A sunflower in origami style on a table
                    - --validation_prompt=A monadikos sunflower on a table in origami style
                    - --validation_prompt_style=A dog in origami style
                    - --validation_prompt_content=a photo of a monadikos sunflower on a table
                    - --sample_times=4
                    - --column_ratio=0.125
                    - --entity=elysiaareudi-discord
                    - --content_rare_word=monadikos
                    - --class_word=sunflower
                    - --style_rare_word=origami style
                    - --super_word=dog
                    - --heatmap_map_size=64
                    - --heatmap_alpha=0.5
                    - --heatmap_steps=100
                    - --focus=false
                    - --with_align_loss=true
                    - --align_loss_weight=0.2
                    - --with_gsa_loss=false
                    - --gsa_loss_weight=0.4
                    - --sig_type=last
                    - --with_svd_init=true
                    - --use_base_weight=true
                    - --alpha=1.0
                    - --min_rank_content=32
                    - --min_rank_style=24
                    - --timestep_mode=priecewise
                    - --use_time_control=true
                codePath: train_unziplora.py
                codePathLocal: train_unziplora.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "226300428288"
                        used: "73216950272"
                email: elysiaareudi@gmail.com
                executable: /home/xzh/miniconda3/envs/unziplora/bin/python3.11
                git:
                    commit: e01dede51f4c14e4dff9ccc6025ad0aa03e0056a
                    remote: https://github.com/aiirudi/UnZipLoRA.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-7116146a-2e38-32ca-5a0d-4408f8e65c81
                host: amax
                memory:
                    total: "134809575424"
                os: Linux-5.15.0-70-generic-x86_64-with-glibc2.31
                program: /home/xzh/xzh/UnZipLoRA-fine/train_unziplora.py
                python: CPython 3.11.15
                root: /home/xzh/xzh/UnZipLoRA-fine
                startedAt: "2026-06-22T15:45:51.106741Z"
                writerId: ysthqykaj0tytvzyy5yhwtf8y96afxis
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
                - 105
            "3":
                - 2
                - 13
                - 18
                - 61
            "4": 3.11.15
            "5": 0.24.2
            "6": 4.42.3
            "12": 0.24.2
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.0001
adam_weight_decay_text_encoder:
    value: 0.001
align_loss_weight:
    value: 0.2
allow_tf32:
    value: false
alpha:
    value: 1
cache_dir:
    value: null
caption_column:
    value: null
center_crop:
    value: false
checkpointing_steps:
    value: 200
checkpoints_total_limit:
    value: null
class_data_dir:
    value: null
class_data_dir_2:
    value: null
class_prompt:
    value: null
class_prompt_2:
    value: null
class_word:
    value: sunflower
column_ratio:
    value: 0.125
content_forward_prompt:
    value: A monadikos sunflower
content_learning_rate:
    value: 5e-05
content_rare_word:
    value: monadikos
crops_coords_top_left_h:
    value: 0
crops_coords_top_left_w:
    value: 0
dataloader_num_workers:
    value: 0
dataset_config_name:
    value: null
dataset_name:
    value: null
enable_xformers_memory_efficient_attention:
    value: false
entity:
    value: elysiaareudi-discord
feature_prompt:
    value: null
focus:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gsa_loss_weight:
    value: 0.4
heatmap_alpha:
    value: 0.5
heatmap_map_size:
    value: 64
heatmap_steps:
    value: 100
hub_model_id:
    value: null
hub_token:
    value: null
image_column:
    value: image
instance_data_dir:
    value: /home/xzh/xzh/UnZipLoRA-fine/instance_data/origami_sunflower
instance_prompt:
    value: A monadikos sunflower in origami style
local_rank:
    value: -1
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 0
max_grad_norm:
    value: 1
max_train_steps:
    value: 600
min_rank_content:
    value: 32
min_rank_style:
    value: 24
mixed_precision:
    value: fp16
name:
    value: unziplora+M1+M2(fused)
num_class_images:
    value: 100
num_train_epochs:
    value: 600
num_validation_images:
    value: 4
optimizer:
    value: AdamW
output_dir:
    value: models/origami_sunflower/origami_sunflower
pretrained_model_name_or_path:
    value: /home/xzh/xzh/pretrained/sd_xl_base_1.0
pretrained_vae_model_name_or_path:
    value: null
prior_generation_precision:
    value: null
prior_loss_weight:
    value: 1
prior_loss_weight_2:
    value: 1
prodigy_beta3:
    value: null
prodigy_decouple:
    value: true
prodigy_safeguard_warmup:
    value: true
prodigy_use_bias_correction:
    value: true
push_to_hub:
    value: false
rank:
    value: 64
repeats:
    value: 1
report_to:
    value: wandb
resolution:
    value: 1024
resume_from_checkpoint:
    value: null
revision:
    value: null
sample_batch_size:
    value: 4
sample_times:
    value: 4
scale_lr:
    value: false
seed:
    value: 0
sig_type:
    value: last
similarity_lambda:
    value: 0.5
snr_gamma:
    value: null
style_forward_prompt:
    value: A sunflower in origami style
style_learning_rate:
    value: 5e-05
style_rare_word:
    value: origami style
super_word:
    value: dog
tags:
    value: []
text_encoder_lr:
    value: 5e-06
timestep_mode:
    value: priecewise
train_batch_size:
    value: 1
train_text_encoder:
    value: false
use_8bit_adam:
    value: true
use_base_weight:
    value: true
use_time_control:
    value: true
validation_content:
    value: A monadikos sunflower on a table
validation_epochs:
    value: 50
validation_prompt:
    value: A monadikos sunflower on a table in origami style
validation_prompt_content:
    value: a photo of a monadikos sunflower on a table
validation_prompt_style:
    value: A dog in origami style
validation_style:
    value: A sunflower in origami style on a table
wandb_dir:
    value: null
weight_learning_rate:
    value: 0.005
with_accumulate_cone:
    value: true
with_align_loss:
    value: true
with_finetune_mask:
    value: false
with_freeze_unet:
    value: true
with_grad_record:
    value: false
with_gsa_loss:
    value: false
with_image_per_validation:
    value: false
with_no_overlap_first:
    value: true
with_one_shot:
    value: true
with_period_column_separation:
    value: true
with_prior_preservation:
    value: false
with_saved_per_validation:
    value: false
with_svd_init:
    value: true
